config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,:controllers => { :registrations => 'users',
  :omniauth_callbacks => 'callbacks' }
  root to: 'welcome#index'
  get 'index1', to: 'welcome#index1'
   get 'about', to: 'welcome#about'
   get 'element', to: 'welcome#element'
   get 'contact', to: 'welcome#contact'
   get 'portfolio', to: 'welcome#portfolio'
   #get 'services', to: 'welcome#services'
  get 'show1', to: 'projects#show1'
  get'view1', to: 'projects#view1'
  post'status', to: 'assigns#status'
  post'final_status', to: 'projects#final_status'
  get'image_download', to: 'projects#image_download'
  resources :projects
  resources :assigns
end

app/models/ability.rb
#
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
      can :dashboard

    elsif user.role == 'Project Manager'
      can :manage, User do |project|
        project.id == user.id
      end
    else
      can :index, User do |u|
        u.id == user.id
      end
    end
  end
end

app/models/application_record.rb
#
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign.rb
#
class Assign < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :user_id, presence: true
end

app/models/project.rb
#
class Project < ApplicationRecord
  has_many :assigns
  has_many :users, :through => 'assigns'
  # has_attached_file :avatar, :styles =>
  # {
  #   :thumb => '200x200#',
  #   :small  => '400x400>',
  #   :medium => '800x800'
  # }, :default_url => 'public/default_image.png'

  # validates_attachment :avatar, content_type:
  # { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }
  # validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  # validates :requirements, presence: true
  # validates :domain, presence: true
end

app/models/user.rb
#
class User < ApplicationRecord
  has_many :assigns
  has_many :projects, :through => 'assigns'
  devise :database_authenticatable, :registerable, :confirmable,
  :omniauthable, :recoverable, :rememberable, :validatable
      def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.provider = auth.provider
          user.uid = auth.uid
          user.email = auth.info.email
          user.password = Devise.friendly_token[0, 20]
        end
      end
      validate :password_regex
      private

  def password_regex
    return if password.blank? || password =~ /\A(?=.*\d)(?=.*[A-Z])(?=.*\W)[^ ]{7,}\z/

    errors.add :password, 'Password should have more than 7 characters including 1 uppercase letter, 1 number, 1 special character'
  end
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  
end

app/controllers/assigns_controller.rb
#
class AssignsController < ApplicationController

  def index
   @project = Project.where(user_id: current_user.id)
   @tester = User.where(role: 'Tester')
   @designer = User.where(role: 'Designer')
   @developer = User.where(role: 'Developer')
   @assign1 = Assign.where(user_id: current_user).page(params[:page]).per(1)
  end

  def create
    params[:assign][:user_id].each do |uid|
      @dd = Assign.create(user_id: uid, project_id: params[:assign][:project_id])
       end
  end

  def status

    @status=params[:status]
    @assign2= Assign.find_by('user_id = ? and project_id =?',current_user.id, params[:assign] )
    @assign2.update_attributes(status: @status)
  end
end

app/controllers/callbacks_controller.rb
#
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in_and_redirect @user
  end
end

app/controllers/projects_controller.rb
#
class ProjectsController < ApplicationController
  def index
    @project = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @user = User.find(current_user.id)
    authorize! :manage, @user
    @project = Project.new(create_params)
     if @project.save
       flash[:success] = 'Project got created successfully'
       redirect_to show1_path
     else
       render 'new'
     end
  end

  def view1
    @user = User.find(current_user.id)
    authorize! :manage, @user
    @project = Project.where(user_id: current_user.id).page(params[:page]).per(1)

  end

   def update
     @project = Project.find(params[:id])
     if @project.update_attributes(update_params)
       redirect_to show1_path
       flash[:success] = 'Project got updated successfully'
     end
   end

   def show
     @user = User.find(current_user.id)
     authorize! :manage, @user
     @show = Project.all.page(params[:page]).per(3)
   end

   def show1
     @user = User.find(current_user.id)
     authorize! :manage, @user
       @project = Project.where(user_id: current_user.id).page(params[:page]).per(1)
   end

   def edit
     @user = User.find(current_user.id)
     authorize! :manage, @user
     @project = Project.find(params[:id])

    end

    def destroy
      @user = User.find(current_user.id)
      authorize! :manage, @user
      @project = Project.find(params[:id])
      if @project.destroy
        flash[:success] = 'Project got deleted successfully'
        redirect_to view1_path
      end
    end

    def final_status

      @user = User.find(current_user.id)
      authorize! :manage, @user
       @final_status = params[:final_status]
       @pro = Project.find(params[:project_id])
       @pro.update_attributes(:final_status => @final_status)
       redirect_to view1_path
    end

    private

    def create_params
      params.require(:project).permit(:name, :requirements, :domain, :user_id,
      #  :avatar, :document
       )
    end
    def update_params
      params.require(:project).permit(:name, :requirements, :domain,
      #  :avatar, :document
       )
    end
end

app/controllers/users_controller.rb
#
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!

  def index
    super
  end

  def new
    @user = User.new
  end

  def view
  end

  def create
    @user = User.new(pram_parms)
    if @user.save
      flash[:success] = 'Signed up Successfully'
      redirect_to new_user_session_path
    else
      render 'new'
    end
  end

  def edit
    super
  end

  def user_home
  end

  private

  def pram_parms
    params.require(:user).permit(:name.downcase, :password, :email.downcase, :role)
  end
end

app/controllers/welcome_controller.rb
#
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about, :element, :contact, :portfolio, :services]

  def index
    if user_signed_in?
      redirect_to index1_path
    end
  end

  def about
  end

  def element
  end

  def contact
  end

  def portfolio
  end

  def services
  end

  def index1
    @role = current_user.role
    if current_user.role == 'admin'
      redirect_to rails_admin_path
    end
  end

end

app/helpers/application_helper.rb
#
module ApplicationHelper
  def name
    @name = current_user.name
  end


end

app/helpers/devise_helper.rb
#
module DeviseHelper
  def role
    role = ['Project Manager', 'Tester', 'Designer', 'Developer']
 end

end

app/views/assigns/index.html.erb
<%if current_user.role == "Project Manager"%>
<div class="box" style="height:800px;">

  <%=render 'layouts/head'%>

<%= render 'layouts/nav' %>

<form method='post' action ='<% assigns_path%>'  id="target" style="color:black;">

   <center>

         <h3>Select Project </h3>

         <%= collection_select(:assign, :project_id, @project, :id, :name, {multiple: :false})%>
</center>
      <br>

      <div ><center>
        <fieldset>
      <%=  "SELECT ANY TWO DEVELOPER" %><br>
         <%= collection_select(:assign, :user_id, @developer, :id, :name, {include_blank: false, include_hidden: false}, {multiple: :true, class: 'dp_second'})%>
    </fieldset></center>  </div>

      <div><center><fieldset>
      <%= "SELECT ANY TWO DESIGNER" %><br>
         <%= collection_select(:assign, :user_id, @designer, :id, :name, {include_blank: false, include_hidden: false}, {multiple: :true, class: 'dp_third'})%>
    </fieldset></center>  </div>

      <div ><center><fieldset>

         <%=  "SELECT ANY TWO TESTER" %><br>
         <%= collection_select(:assign, :user_id, @tester, :id, :name,  {include_blank: false, include_hidden: false}, {multiple: :true, class: 'dp_first'})%>
    </fieldset></center>  </div>

 <center >
      <input type='submit' value='submit' data-confirm="Are you sure?" class="btn btn-primary btn-lg btn-block" style="width:10%;margin-top:30px;height:40px">
      </center>

</form>
<ul class="bg-bubbles">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li ></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>

</ul>
</div>

<%=render 'layouts/footor'%>
<%else%>
<div class="box" style="height:auto;">

  <%=render 'layouts/head'%>
  <%=render 'layouts/nav1'%>
<%if @assign1.present? %>

  <center><h2>These are assigned projects</h2> <br> </center>
  <center>
<fieldset>
        <form method='post' , action= "/status">

         <% @assign1.each do |t| %>
         <div class="form-group">
            <div class="control-label col-sm-2">
               <strong>Project Name :</strong>
            </div>
              <div class="col-sm-3">
         <input type="text" value = "<%= Project.find(t.project_id).name %>" readonly class="form-control" />
         </div><br>
      <%=hidden_field_tag :assign, :project_id, :value => t.project_id%>
         <fieldset>
            <div class= "h">
               <%= label_tag "Requirements:"%>
               <%= Project.find(t.project_id).requirements.html_safe %>
            </div>
         </fieldset>
         <div class="form-group">
            <div class="control-label col-sm-2">
               <strong>Domain :</strong>
            </div>
              <div class="col-sm-3">
         <input type="text" value = "<%= Project.find(t.project_id).domain %>" readonly class="form-control"/>
       </div><br>
            <div class= "img">
               <img id="myImg" src= "<%=Project.find( t.project_id).avatar.url(:thumb)%>" alt="Trolltunga, Norway" width="300" height="200">
               <div id="myModal" class="modal">
                  <span class="close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>
                  <img class="modal-content" id="img01">
                  <div id="caption"></div>
               </div>
            </div><br>
            <div class="form-group">
               <div class="control-label col-sm-2">
                  <strong> Status :</strong>
               </div>
               <div class="col-sm-3">

            <% if t.status  == "Done" %>

              <%= t.status %>
            <% else %>
            <%= label_tag @status, 'Completed' %>
              <%= radio_button_tag :status,"Done"  %>
              <%= label_tag @status, 'Pending' %>
              <%=radio_button_tag :status, "Pending" %><br class="btn btn-primary btn-lg btn-block">
              <%= submit_tag  "submit", :onclick => "alert('Status is Submitted')",:class => "btn btn-primary"%>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <% end %>
          </br>
</div>
<br>
</div>
</div>
</div>
     <%end%>

   </fieldset>
   <div>
   <%= paginate @assign1 %></div>
 </center>

<%else%>
<center>
<MARQUEE >
  <h1>No projects are assigned yet<h1>
    <%=link_to 'Logout', destroy_user_session_path, method: :delete%>
</MARQUEE></center>

<div><center>
  <img src="project-management.jpg"  style="width:1000px;height:500px;">  </center>
 </div>
<%end%>
<ul class="bg-bubbles">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li ></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li ></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>

</ul>
</div>
<%=render 'layouts/footor'%>

<%end%>

<script type='text/javascript'>
  $( "#target" ).submit(function( event ) {
    if ($('.dp_first option:selected').length != 2){
      event.preventDefault();
      alert('Please choose exactly 2 Tester ...');
    }
  });
</script>
<script type='text/javascript'>
  $( "#target" ).submit(function( event ) {
    if ($('.dp_second option:selected').length != 2){
      event.preventDefault();
      alert('Please choose exactly 2 Devloper ...');
    }
  });
</script>
<script type='text/javascript'>
  $( "#target" ).submit(function( event ) {
    if ($('.dp_third option:selected').length != 2){
      event.preventDefault();
      alert('Please choose exactly 2 Designer ...');
    }
  });
</script>
<script>
   var modal = document.getElementById('myModal');
   var img = document.getElementById('myImg');
   var modalImg = document.getElementById("img01");
   var captionText = document.getElementById("caption");
   img.onclick = function(){
       modal.style.display = "block";
       modalImg.src = this.src;
       captionText.innerHTML = this.alt;
   }
</script>

app/views/layouts/_footor.html.erb
<footer role="contentinfo" style="position:absolute;">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2 class="fh5co-footer-title">About</h2>
        <p> Shashank Enterprises</p>
      </div>
      <div class="col-md-5">
        <h2 class="fh5co-footer-title">Offices</h2>
        <div class="row">
          <div class="col-md-6">
          <h3 class="h4">Dublin Ireland</h3>
          <address>540 Apartment no 5 <br>North Circular Road, Dublin 10016</address>
          </div>
          <div class="col-md-6">
            <h3 class="h4">India</h3>
            <address> Chandigarh<br> Punjab ,134116</address>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <h2 class="fh5co-footer-title">Links</h2>
        <ul class="fh5co-footer-links">
          <li><a href="www.facebook.com"></a></li>
          <li><a href="https://www.smashingmagazine.com/">Smashingmagazine</a></li>
          <li><a href="https://www.smashingmagazine.com/">A List Apart</a></li>
          <li><a href="https://creativemarket.com/">Creative Market</a></li>
        </ul>
      </div>
      <div class="col-md-2">
        <h2 class="fh5co-footer-title">Connect</h2>
        <ul class="fh5co-footer-links">
          <li><a href="https://twitter.com/" class="fh5co-link"><i class="fa fa-twitter"></i>Twitter</a></li>
          <li><a href="https://facebook.com/" class="fh5co-link"><i class="fa fa-facebook-square"></i>Facebook</a></li>
          <li><a href="https://github.com/" class="fh5co-link"><i class="fa fa-github"></i>Github</a></li>
          <li><a href="https://linkedin.com/" class="fh5co-link"><i class="fa fa-linkedin-square"></i>LinkedIn</a></li>
          <li><a href="https://plus.google.com/" class="fh5co-link"><i class="fa fa-google"></i>Google Plus</a></li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="fh5co-copyright">
          <p class="pull-left">&copy;	Shashank Enterprises 2017. All Rights Reserved. <br> contact <a href="mailto:http://www.facebook.com "target="_blank">facebook.com</a>
          <ul class="pull-right fh5co-footer-social">
            <li><a href="https://facebook.com/"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://instagram.com/"><i class="fa fa-instagram"></i></a></li>
            <li><a href="https://linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</footer>

app/views/layouts/_head.html.erb
<div> <center>  <h2 class="head"> Shashank Enterprises</h2></center>

  <center>  <h4 class="head2">ONLINE PROJECT MANAGEMENT SYSTEM</h4></center></div>

app/views/layouts/_icons.html.erb
<div class=overlay2>
<a target="_blank" title="follow me on twitter" href="http://www.twitter.com">
  <img alt="follow me on twitter" src="//login.create.net/images/icons/user/twitter_30x30.png" border=0></a><br>
  <a target="_blank" title="find us on Facebook" href="http://www.facebook.com">
    <img alt="follow me on facebook" src="//login.create.net/images/icons/user/facebook_30x30.png" border=0></a>
    </div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div>

     <ul class="nav nav-tabs" >

        <li role="presentation"><a href="/index1" class="btn btn-primary fh5co-hero-btn">Home</a></li>
        <li role="presentation"><a href="/projects/new" class="btn btn-primary fh5co-hero-btn">Add New Project</a></li>
        <li role="presentation"><a href="/show1" class="btn btn-primary fh5co-hero-btn">Show Projects !</a></li>
        <li role="presentation"><a href="/assigns" class="btn btn-primary fh5co-hero-btn">Assign Projects</a></li>
        <li role="presentation"><a href="/view1" class="btn btn-primary fh5co-hero-btn">View Team</a></li>
       <ul class="nav navbar-right">
        <li role="presentation"><a href=" /users/sign_out" class="btn btn-primary fh5co-hero-btn" data-method="delete">Logout</a></li>

    </div>
  </div>
</nav>

app/views/layouts/_nav1.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div >

     <ul class="nav nav-tabs">
        <li role="presentation"><a href="/index1" class="btn btn-primary fh5co-hero-btn">Home</a></li>
    <li role="presentation"><a href="/assigns" class="btn btn-primary fh5co-hero-btn">Assign Projects</a></li>
      <ul class="nav navbar-right">
        <li role="presentation"><a href=" /users/sign_out" class="btn btn-primary fh5co-hero-btn" data-method="delete">Logout</a></li>

        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineProjectManagementSystem</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/projects/_errors.html.erb
<%if flash[:error]%>
<div class='alert alert-danger'><%=flash[:error]%></div>
<%end%>
<%if @project.errors.any? %>
<div class='alert alert-danger'>
<%@project.errors.full_messages.each do|msg|%>
  <%=msg%>
  <br>
<%end%>
</div>
<%end%>

app/views/projects/edit.html.erb
<%= tinymce %>
<div class="box">
<%=render 'errors' ,project: @project %>
<%=render 'layouts/head'%>

<%= render 'layouts/nav' %>

 <center>
  <p></p><p></p>
<h1>Edit Project Details</h1>
<p></p><p></p>
<%= form_for @project, :url=>{:action=>'update'} do |f| %>
<div style="color:black;" >
  <%= f.label :Name%>
</div>
<div style="color:black;width:20%">
  <%= f.text_field :name %>
</div>
<div style="color:black;">
<%= f.label :Requirements%>
</div>

<div style="color:black;">
<%= f.text_area :requirements, :class => "tinymce" %>
</div>
<div style="color:black;width:20%">
<%= f.label :Domain%>
</div>
<div style="color:black;width:20%">
<%= f.text_field :domain%>
</div>
<div style="color:black;">
 <%= f.label :avatar %>
 <%= f.file_field :avatar ,:style=> "width:250px;" %>
</div>

<%= f.hidden_field :user_id, :value => current_user.id %>


<div>

<%= f.submit 'Update' ,:class => "btn btn-primary btn-lg btn-block" ,:style =>"width:10%;margin-top:30px;height:40px"%>
</div>
<ul class="bg-bubbles">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li ></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>

</ul>
</div>
<%end%>
</center>
<%=render 'layouts/footor'%>

app/views/projects/new.html.erb
<%= tinymce %>
<%if current_user.role == "Project Manager"%>

<%=render 'errors' ,project: @project%>
<div class="box">
 <center>  <%=render 'layouts/head'%></center>
<%= render 'layouts/nav' %>

<center>
  <h3 style="font-style:italic"> Create a new Project </h3>
</center>

     <%= form_for @project ,:html=> { role: 'form', id: 'msform' } do |t| %>

    <fieldset style="background: -o-linear-gradient(top , #50a3a2 0%, #53e3a6 100%);
    background: linear-gradient(to bottom , #50a3a2 0%, #53e3a6 100%);">
      <h2 class="fs-title">Add Details</h2>

      <%= t.text_field :name,  placeholder: "Project Name" ,:required=>true %>
      <%= t.text_field :domain,  placeholder: "Domain Name" ,:required=>true %>

      <input type="button" name="next" class="next action-button" value="Next" style="height:40px;width:100px;float:right;">
    </fieldset>
    <fieldset style="margin-left:0px ;background: -o-linear-gradient(top , #50a3a2 0%, #53e3a6 100%);
    background: linear-gradient(to bottom , #50a3a2 0%, #53e3a6 100%);">
      <h2 class="fs-title">Requirements</h2>

      <div id = 'tinymcediv'   style="width:500px;height:auto; border: 1px solid #ccc;">

       <%= t.text_area :requirements ,:class => "tinymce"%>
       </div>
      <input type="button" name="previous" class="previous action-button" value="Previous" style="height:40px;width:100px;float:right;"/>
      <input type="button" name="next" class="next action-button" value="Next" style="height:40px;width:100px;float:right;"/>
    </fieldset>
    <fieldset style="background: -o-linear-gradient(top , #50a3a2 0%, #53e3a6 100%);
    background: linear-gradient(to bottom , #50a3a2 0%, #53e3a6 100%);">
     
       <%= t.hidden_field :user_id, :value => current_user.id%>

      <input type="button" name="previous" class="previous action-button" value="Previous" style="height:40px;width:100px;float:right;"/>

      <%=t.submit "submit" ,data: { confirm: "Are you sure you want to submit this form?" },:class => "btn btn-primary"%>
    </fieldset>

  <%end%>


  <ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
    <li></li>
		<li></li>
    <li></li>
		<li></li>
		<li></li>
    <li></li>
		<li></li>
    <li></li>
		<li></li>
		<li></li>
    <li></li>
		<li></li>
    <li></li>
		<li></li>
		<li></li>
    <li></li>
		<li></li>

	</ul>
</div>
<%end%>
<%= render 'layouts/footor' %>
<script>
var current_fs, next_fs, previous_fs;
var left, opacity, scale;
var animating;

$(".next").click(function(){
// if(animating) return false;
//animating = true;

var name = $("#project_name").val().length;
var domain = $("#project_domain").val().length;
if (name == 0 || domain == 0 )
{
  return false;
}
else
current_fs = $(this).parent();
next_fs = $(this).parent().next();
next_fs.show();

current_fs.animate({opacity: 0}, {
  step: function(now, mx) {

    scale = 1 - (1 - now) * 0.2;

    left = (now * 50)+"%";

    opacity = 1 - now;
    current_fs.css({
      'transform': 'scale('+scale+')',

    });
    next_fs.css({'left': left, 'opacity': opacity});
  },
  duration: 800,
  complete: function(){
    current_fs.hide();
    // animating = false;
  },

  easing: 'easeInOutBack'
});
});

$(".previous").click(function(){
// if(animating) return false;
//animating = true;

current_fs = $(this).parent();
previous_fs = $(this).parent().prev();

previous_fs.show();
current_fs.animate({opacity: 0}, {
  step: function(now, mx) {

    scale = 0.8 + (1 - now) * 0.2;

    left = ((1-now) * 50)+"%";

    opacity = 1 - now;
    current_fs.css({'left': left});
    previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
  },
  duration: 800,
  complete: function(){
    current_fs.hide();
    // animating = false;
  },

  easing: 'easeInOutBack'
});
});

$(".submit").click(function(){
return false;
})

</script>
<script>
$(function() {

  $("form[name='form']").validate({

    rules: {

    name: "required",
    domain: "required",


    },

    messages: {
      name: "Please enter name",
    domain: "Please enter domain",


    },

    submitHandler: function(msform) {
      form.submit();
    }
  });
});
</script>

app/views/projects/show1.html.erb
<%= tinymce %>
<div class="box" style="height:1200px;"><center>

  <%=render 'layouts/head'%>

</center>
<%= render 'layouts/nav' %>
<%if @project.empty?%>
<h1>
   <center>NO PROJECTS ARE CREATED BY YOU</center>
</h1>
<%else%>
<center>
   <% @project.each do|project|%>
       <div style="height:100%;">
   <fieldset>

         <div>
           <div class="form-group">
              <div class="control-label col-sm-2">
                 <strong>Project Name :</strong>
              </div>
              <div class="col-sm-3">
                 <input type="text" value = "<%= project.name %>" readonly class="form-control"/>
              </div>
           </div>
         </div>
         <br>
         <fieldset>
            <div class= "h">
               <%= label_tag "Requirements:"%>
               <%= project.requirements.html_safe %>
            </div>
         </fieldset>
         <div class="form-group">
            <div class="control-label col-sm-2">
               <strong>Domain :</strong>
            </div>
            <div class="col-sm-3">
               <input type="text" value = "<%= project.domain %>" readonly class="form-control"/>
            </div>
         </div>
         <br>
        
         <div class="form-group">
            <div class="control-label col-sm-2">
               <strong>Final Status :</strong>
            </div>
            <div class="col-sm-3">
               <input type="text" value = "<%= project.final_status %>" readonly class="form-control"/>
            </div>
         </div>

   </fieldset>
   <%= button_to  edit_project_path(project),:style => "width:40px;", method: :get do %>
   <i class="glyphicon glyphicon-pencil" style="width:40px;"></i>
   <% end %>
   <%= button_to project,:style=>"width:40px", method: :delete  ,  data: { confirm: "Are you sure?" } do %>
   <i class="glyphicon glyphicon-trash" style="width:40px"></i>
   <% end %>
   <%end%>
   <%= paginate @project %>
   </div>
</center>
<%end%>
<ul class="bg-bubbles">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li ></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>

</ul>
</div>
<%= render 'layouts/footor'%>

<script>
   var modal = document.getElementById('myModal');
   var img = document.getElementById('myImg');
   var modalImg = document.getElementById("img01");
   var captionText = document.getElementById("caption");
   img.onclick = function(){
       modal.style.display = "block";
       modalImg.src = this.src;
       captionText.innerHTML = this.alt;
   }
</script>